image: alpine

stages:
  - build
  - test

cache:
  paths:
    - target/

maven-build:
  stage: build
  only:
  - master
  script:
    - mvn install -B

bb-test:
  stage: test
  only:
  - master
  script:
    - cat ~/code/checker.py; proj_dir=`pwd`; (cd ~/code; ./checker.py -p ${proj_dir})
